Return-Path: <target-devel-owner@vger.kernel.org>
X-Original-To: lists+target-devel@lfdr.de
Delivered-To: lists+target-devel@lfdr.de
Received: from out1.vger.email (out1.vger.email [IPv6:2620:137:e000::1:20])
	by mail.lfdr.de (Postfix) with ESMTP id C576A7A8D76
	for <lists+target-devel@lfdr.de>; Wed, 20 Sep 2023 22:05:05 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S229593AbjITUFJ (ORCPT <rfc822;lists+target-devel@lfdr.de>);
        Wed, 20 Sep 2023 16:05:09 -0400
Received: from lindbergh.monkeyblade.net ([23.128.96.19]:46672 "EHLO
        lindbergh.monkeyblade.net" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
        with ESMTP id S229630AbjITUFI (ORCPT
        <rfc822;target-devel@vger.kernel.org>);
        Wed, 20 Sep 2023 16:05:08 -0400
Received: from mail-pf1-f175.google.com (mail-pf1-f175.google.com [209.85.210.175])
        by lindbergh.monkeyblade.net (Postfix) with ESMTPS id 32150B9
        for <target-devel@vger.kernel.org>; Wed, 20 Sep 2023 13:05:02 -0700 (PDT)
Received: by mail-pf1-f175.google.com with SMTP id d2e1a72fcca58-690d2441b95so90882b3a.1
        for <target-devel@vger.kernel.org>; Wed, 20 Sep 2023 13:05:02 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20230601; t=1695240301; x=1695845101;
        h=content-transfer-encoding:mime-version:references:in-reply-to
         :message-id:date:subject:cc:to:from:x-gm-message-state:from:to:cc
         :subject:date:message-id:reply-to;
        bh=J6sADAUYGnxlFZ13cq6+2ars1Uyhtlzopqm8/aC57oE=;
        b=ZmfDd+vkbQ/fi1Tr3U2hGuWQGCUyi4MR2eXPCp2py0oEdunDzr/gZF5YCJV3GyAIRW
         Hw8I4+/Pl3jwS++vQw9DGcoSOF5JqJzA8iGD5vXw9TcbBCmU7yft7CMEMw18m33KhMu9
         UNbuLsSNfuLSHoG+wNkYZQHQWnbiTiZw+Vqv2a1wGSDVJqSaTU+ZY4Ix98z4iIIb9THA
         CYVmPn4fX9GcQstOHp51ptSKC2mM2ii0zWsqxnYLniCylYR/4XtU5jMQFqGIn7JSCaO/
         nA/hZvp+Bu1ayPCwL3w5/ItVY4I3TnwIdsrw7Vpv417Kh+a2AArvsz2lS7adI5v6xTF1
         1AEQ==
X-Gm-Message-State: AOJu0Yw2qbLcJw0/ytW+b8l1D4lGd+108LJVAdJVoClnlz0Xw9RF3qXA
        1TU0o6zdUAVNAhseAJWvhUg=
X-Google-Smtp-Source: AGHT+IFmlnlyeSwJ96PrzDczXwcPU4hNtF3qUE8bqifqWGBnWBeBozLc7paDZ7oUh+Ow9O7XwAXzag==
X-Received: by 2002:a05:6a20:1608:b0:130:7ef2:ff21 with SMTP id l8-20020a056a20160800b001307ef2ff21mr8580452pzj.19.1695240301391;
        Wed, 20 Sep 2023 13:05:01 -0700 (PDT)
Received: from bvanassche-linux.mtv.corp.google.com ([2620:15c:211:201:b0c6:e5b6:49ef:e0bd])
        by smtp.gmail.com with ESMTPSA id c70-20020a633549000000b0054fe7736ac1sm10035341pga.76.2023.09.20.13.04.59
        (version=TLS1_3 cipher=TLS_AES_256_GCM_SHA384 bits=256/256);
        Wed, 20 Sep 2023 13:05:00 -0700 (PDT)
From:   Bart Van Assche <bvanassche@acm.org>
To:     "Martin K . Petersen" <martin.petersen@oracle.com>
Cc:     Mike Christie <mchristi@redhat.com>,
        Christoph Hellwig <hch@lst.de>, target-devel@vger.kernel.org,
        Bart Van Assche <bvanassche@acm.org>,
        Jonathan Corbet <corbet@lwn.net>,
        Sagi Grimberg <sagi@grimberg.me>,
        Jason Gunthorpe <jgg@ziepe.ca>,
        Leon Romanovsky <leon@kernel.org>,
        Mike Christie <michael.christie@oracle.com>,
        Maurizio Lombardi <mlombard@redhat.com>,
        Dmitry Bogdanov <d.bogdanov@yadro.com>,
        Konstantin Shelekhin <k.shelekhin@yadro.com>,
        Peilin Ye <peilin.ye@bytedance.com>,
        Azeem Shaikh <azeemshaikh38@gmail.com>,
        Kees Cook <keescook@chromium.org>,
        Jakub Kicinski <kuba@kernel.org>,
        David Howells <dhowells@redhat.com>,
        Al Viro <viro@zeniv.linux.org.uk>
Subject: [PATCH v2 3/3] scsi: target: Change nab@linux-iscsi.org into nab@kernel.org
Date:   Wed, 20 Sep 2023 13:00:21 -0700
Message-ID: <20230920200232.3721784-4-bvanassche@acm.org>
X-Mailer: git-send-email 2.42.0.459.ge4e396fd5e-goog
In-Reply-To: <20230920200232.3721784-1-bvanassche@acm.org>
References: <20230920200232.3721784-1-bvanassche@acm.org>
MIME-Version: 1.0
Content-Transfer-Encoding: 8bit
X-Spam-Status: No, score=-1.4 required=5.0 tests=BAYES_00,
        FREEMAIL_FORGED_FROMDOMAIN,FREEMAIL_FROM,HEADER_FROM_DIFFERENT_DOMAINS,
        RCVD_IN_DNSWL_NONE,RCVD_IN_MSPIKE_H2,SPF_HELO_NONE,SPF_PASS
        autolearn=no autolearn_force=no version=3.4.6
X-Spam-Checker-Version: SpamAssassin 3.4.6 (2021-04-09) on
        lindbergh.monkeyblade.net
Precedence: bulk
List-ID: <target-devel.vger.kernel.org>
X-Mailing-List: target-devel@vger.kernel.org

Nicholas A. Bellinger owns both email addresses. Perform this
replacement because the linux-iscsi.org domain name no longer has any MX
records associated. This patch has been generated by running the
following shell command:

    git grep -li 'nab@linux-iscsi.org' |
        while read f; do
	    awk '{ if (match($0, "Copyright") == 0) gsub("nab@[lL]inux-i[sS][cC][sS][iI].org", "nab@kernel.org"); print $0 }' <$f >/tmp/awk.tmp &&
	        mv /tmp/awk.tmp $f
	done

Note: I received the following reply after having sent an email to
nab@kernel.org: "I'm sorry to have to inform you that your message
could not be delivered to one or more recipients. It's attached below.
For further assistance, please send mail to postmaster. If you do so,
please include this problem report. You can delete your own text from
the attached returned message. The mail system."

Signed-off-by: Bart Van Assche <bvanassche@acm.org>
---
 Documentation/target/tcm_mod_builder.rst          | 2 +-
 drivers/infiniband/ulp/isert/ib_isert.c           | 4 ++--
 drivers/target/iscsi/iscsi_target.c               | 4 ++--
 drivers/target/iscsi/iscsi_target_auth.c          | 2 +-
 drivers/target/iscsi/iscsi_target_configfs.c      | 2 +-
 drivers/target/iscsi/iscsi_target_datain_values.c | 2 +-
 drivers/target/iscsi/iscsi_target_device.c        | 2 +-
 drivers/target/iscsi/iscsi_target_erl0.c          | 2 +-
 drivers/target/iscsi/iscsi_target_erl1.c          | 2 +-
 drivers/target/iscsi/iscsi_target_erl2.c          | 2 +-
 drivers/target/iscsi/iscsi_target_login.c         | 2 +-
 drivers/target/iscsi/iscsi_target_nego.c          | 2 +-
 drivers/target/iscsi/iscsi_target_nodeattrib.c    | 2 +-
 drivers/target/iscsi/iscsi_target_parameters.c    | 2 +-
 drivers/target/iscsi/iscsi_target_seq_pdu_list.c  | 2 +-
 drivers/target/iscsi/iscsi_target_stat.c          | 2 +-
 drivers/target/iscsi/iscsi_target_tmr.c           | 2 +-
 drivers/target/iscsi/iscsi_target_tpg.c           | 2 +-
 drivers/target/iscsi/iscsi_target_util.c          | 2 +-
 drivers/target/target_core_configfs.c             | 2 +-
 drivers/target/target_core_fabric_configfs.c      | 2 +-
 drivers/target/target_core_fabric_lib.c           | 2 +-
 drivers/target/target_core_file.c                 | 2 +-
 drivers/target/target_core_iblock.c               | 2 +-
 drivers/target/target_core_pscsi.c                | 2 +-
 drivers/target/target_core_stat.c                 | 2 +-
 26 files changed, 28 insertions(+), 28 deletions(-)

diff --git a/Documentation/target/tcm_mod_builder.rst b/Documentation/target/tcm_mod_builder.rst
index 9bfc9822e2bd..3e3e15d36a19 100644
--- a/Documentation/target/tcm_mod_builder.rst
+++ b/Documentation/target/tcm_mod_builder.rst
@@ -146,4 +146,4 @@ Future TODO items
 
 October 5th, 2010
 
-Nicholas A. Bellinger <nab@linux-iscsi.org>
+Nicholas A. Bellinger <nab@kernel.org>
diff --git a/drivers/infiniband/ulp/isert/ib_isert.c b/drivers/infiniband/ulp/isert/ib_isert.c
index 00a7303c8cc6..3abd958c6f20 100644
--- a/drivers/infiniband/ulp/isert/ib_isert.c
+++ b/drivers/infiniband/ulp/isert/ib_isert.c
@@ -4,7 +4,7 @@
  *
  * (c) Copyright 2013 Datera, Inc.
  *
- * Nicholas A. Bellinger <nab@linux-iscsi.org>
+ * Nicholas A. Bellinger <nab@kernel.org>
  *
  ****************************************************************************/
 
@@ -2660,7 +2660,7 @@ static void __exit isert_exit(void)
 }
 
 MODULE_DESCRIPTION("iSER-Target for mainline target infrastructure");
-MODULE_AUTHOR("nab@Linux-iSCSI.org");
+MODULE_AUTHOR("nab@kernel.org");
 MODULE_LICENSE("GPL");
 
 module_init(isert_init);
diff --git a/drivers/target/iscsi/iscsi_target.c b/drivers/target/iscsi/iscsi_target.c
index b516c2893420..5b2138ff3c09 100644
--- a/drivers/target/iscsi/iscsi_target.c
+++ b/drivers/target/iscsi/iscsi_target.c
@@ -4,7 +4,7 @@
  *
  * (c) Copyright 2007-2013 Datera, Inc.
  *
- * Author: Nicholas A. Bellinger <nab@linux-iscsi.org>
+ * Author: Nicholas A. Bellinger <nab@kernel.org>
  *
  ******************************************************************************/
 
@@ -4846,7 +4846,7 @@ int iscsit_release_sessions_for_tpg(struct iscsi_portal_group *tpg, int force)
 
 MODULE_DESCRIPTION("iSCSI-Target Driver for mainline target infrastructure");
 MODULE_VERSION("4.1.x");
-MODULE_AUTHOR("nab@Linux-iSCSI.org");
+MODULE_AUTHOR("nab@kernel.org");
 MODULE_LICENSE("GPL");
 
 module_init(iscsi_target_init_module);
diff --git a/drivers/target/iscsi/iscsi_target_auth.c b/drivers/target/iscsi/iscsi_target_auth.c
index c8a248bd11be..5363e3621ef7 100644
--- a/drivers/target/iscsi/iscsi_target_auth.c
+++ b/drivers/target/iscsi/iscsi_target_auth.c
@@ -4,7 +4,7 @@
  *
  * (c) Copyright 2007-2013 Datera, Inc.
  *
- * Author: Nicholas A. Bellinger <nab@linux-iscsi.org>
+ * Author: Nicholas A. Bellinger <nab@kernel.org>
  *
  ******************************************************************************/
 
diff --git a/drivers/target/iscsi/iscsi_target_configfs.c b/drivers/target/iscsi/iscsi_target_configfs.c
index 1cff6052e820..e98b896e5a11 100644
--- a/drivers/target/iscsi/iscsi_target_configfs.c
+++ b/drivers/target/iscsi/iscsi_target_configfs.c
@@ -5,7 +5,7 @@
  *
  * (c) Copyright 2007-2013 Datera, Inc.
  *
- * Author: Nicholas A. Bellinger <nab@linux-iscsi.org>
+ * Author: Nicholas A. Bellinger <nab@kernel.org>
  *
  ****************************************************************************/
 
diff --git a/drivers/target/iscsi/iscsi_target_datain_values.c b/drivers/target/iscsi/iscsi_target_datain_values.c
index 2d44781be3c6..7e81afa50144 100644
--- a/drivers/target/iscsi/iscsi_target_datain_values.c
+++ b/drivers/target/iscsi/iscsi_target_datain_values.c
@@ -4,7 +4,7 @@
  *
  * (c) Copyright 2007-2013 Datera, Inc.
  *
- * Author: Nicholas A. Bellinger <nab@linux-iscsi.org>
+ * Author: Nicholas A. Bellinger <nab@kernel.org>
  *
  ******************************************************************************/
 
diff --git a/drivers/target/iscsi/iscsi_target_device.c b/drivers/target/iscsi/iscsi_target_device.c
index b565ce3b2677..613d86c48a7e 100644
--- a/drivers/target/iscsi/iscsi_target_device.c
+++ b/drivers/target/iscsi/iscsi_target_device.c
@@ -5,7 +5,7 @@
  *
  * (c) Copyright 2007-2013 Datera, Inc.
  *
- * Author: Nicholas A. Bellinger <nab@linux-iscsi.org>
+ * Author: Nicholas A. Bellinger <nab@kernel.org>
  *
  ******************************************************************************/
 
diff --git a/drivers/target/iscsi/iscsi_target_erl0.c b/drivers/target/iscsi/iscsi_target_erl0.c
index 07e9cf431edd..97f366fea0f2 100644
--- a/drivers/target/iscsi/iscsi_target_erl0.c
+++ b/drivers/target/iscsi/iscsi_target_erl0.c
@@ -5,7 +5,7 @@
  *
  * (c) Copyright 2007-2013 Datera, Inc.
  *
- * Author: Nicholas A. Bellinger <nab@linux-iscsi.org>
+ * Author: Nicholas A. Bellinger <nab@kernel.org>
  *
  ******************************************************************************/
 
diff --git a/drivers/target/iscsi/iscsi_target_erl1.c b/drivers/target/iscsi/iscsi_target_erl1.c
index f460a66c0e7c..49acae57279c 100644
--- a/drivers/target/iscsi/iscsi_target_erl1.c
+++ b/drivers/target/iscsi/iscsi_target_erl1.c
@@ -4,7 +4,7 @@
  *
  * (c) Copyright 2007-2013 Datera, Inc.
  *
- * Author: Nicholas A. Bellinger <nab@linux-iscsi.org>
+ * Author: Nicholas A. Bellinger <nab@kernel.org>
  *
  ******************************************************************************/
 
diff --git a/drivers/target/iscsi/iscsi_target_erl2.c b/drivers/target/iscsi/iscsi_target_erl2.c
index 18e88d2ea5fd..6bee1eaa8012 100644
--- a/drivers/target/iscsi/iscsi_target_erl2.c
+++ b/drivers/target/iscsi/iscsi_target_erl2.c
@@ -5,7 +5,7 @@
  *
  * (c) Copyright 2007-2013 Datera, Inc.
  *
- * Author: Nicholas A. Bellinger <nab@linux-iscsi.org>
+ * Author: Nicholas A. Bellinger <nab@kernel.org>
  *
  ******************************************************************************/
 
diff --git a/drivers/target/iscsi/iscsi_target_login.c b/drivers/target/iscsi/iscsi_target_login.c
index 90b870f234f0..ff9a75868c12 100644
--- a/drivers/target/iscsi/iscsi_target_login.c
+++ b/drivers/target/iscsi/iscsi_target_login.c
@@ -4,7 +4,7 @@
  *
  * (c) Copyright 2007-2013 Datera, Inc.
  *
- * Author: Nicholas A. Bellinger <nab@linux-iscsi.org>
+ * Author: Nicholas A. Bellinger <nab@kernel.org>
  *
  ******************************************************************************/
 
diff --git a/drivers/target/iscsi/iscsi_target_nego.c b/drivers/target/iscsi/iscsi_target_nego.c
index fa3fb5f4e6bc..fbcaccefe4a9 100644
--- a/drivers/target/iscsi/iscsi_target_nego.c
+++ b/drivers/target/iscsi/iscsi_target_nego.c
@@ -4,7 +4,7 @@
  *
  * (c) Copyright 2007-2013 Datera, Inc.
  *
- * Author: Nicholas A. Bellinger <nab@linux-iscsi.org>
+ * Author: Nicholas A. Bellinger <nab@kernel.org>
  *
  ******************************************************************************/
 
diff --git a/drivers/target/iscsi/iscsi_target_nodeattrib.c b/drivers/target/iscsi/iscsi_target_nodeattrib.c
index d63efdefb18e..60d50da7acf1 100644
--- a/drivers/target/iscsi/iscsi_target_nodeattrib.c
+++ b/drivers/target/iscsi/iscsi_target_nodeattrib.c
@@ -4,7 +4,7 @@
  *
  * (c) Copyright 2007-2013 Datera, Inc.
  *
- * Author: Nicholas A. Bellinger <nab@linux-iscsi.org>
+ * Author: Nicholas A. Bellinger <nab@kernel.org>
  *
  ******************************************************************************/
 
diff --git a/drivers/target/iscsi/iscsi_target_parameters.c b/drivers/target/iscsi/iscsi_target_parameters.c
index 5b90c22ee3dc..458ea27dd62d 100644
--- a/drivers/target/iscsi/iscsi_target_parameters.c
+++ b/drivers/target/iscsi/iscsi_target_parameters.c
@@ -4,7 +4,7 @@
  *
  * (c) Copyright 2007-2013 Datera, Inc.
  *
- * Author: Nicholas A. Bellinger <nab@linux-iscsi.org>
+ * Author: Nicholas A. Bellinger <nab@kernel.org>
  *
  ******************************************************************************/
 
diff --git a/drivers/target/iscsi/iscsi_target_seq_pdu_list.c b/drivers/target/iscsi/iscsi_target_seq_pdu_list.c
index 66de2b8de463..496d46c7adc6 100644
--- a/drivers/target/iscsi/iscsi_target_seq_pdu_list.c
+++ b/drivers/target/iscsi/iscsi_target_seq_pdu_list.c
@@ -5,7 +5,7 @@
  *
  * (c) Copyright 2007-2013 Datera, Inc.
  *
- * Author: Nicholas A. Bellinger <nab@linux-iscsi.org>
+ * Author: Nicholas A. Bellinger <nab@kernel.org>
  *
  ******************************************************************************/
 
diff --git a/drivers/target/iscsi/iscsi_target_stat.c b/drivers/target/iscsi/iscsi_target_stat.c
index 367c6468b8e1..a7dddb09ee66 100644
--- a/drivers/target/iscsi/iscsi_target_stat.c
+++ b/drivers/target/iscsi/iscsi_target_stat.c
@@ -5,7 +5,7 @@
  *
  * Copyright (c) 2011-2013 Datera, Inc.
  *
- * Author: Nicholas A. Bellinger <nab@linux-iscsi.org>
+ * Author: Nicholas A. Bellinger <nab@kernel.org>
  *
  ******************************************************************************/
 
diff --git a/drivers/target/iscsi/iscsi_target_tmr.c b/drivers/target/iscsi/iscsi_target_tmr.c
index afc801f255f5..7999fceec62e 100644
--- a/drivers/target/iscsi/iscsi_target_tmr.c
+++ b/drivers/target/iscsi/iscsi_target_tmr.c
@@ -4,7 +4,7 @@
  *
  * (c) Copyright 2007-2013 Datera, Inc.
  *
- * Author: Nicholas A. Bellinger <nab@linux-iscsi.org>
+ * Author: Nicholas A. Bellinger <nab@kernel.org>
  *
  ******************************************************************************/
 
diff --git a/drivers/target/iscsi/iscsi_target_tpg.c b/drivers/target/iscsi/iscsi_target_tpg.c
index f7bac98fd4fe..0c1763d99675 100644
--- a/drivers/target/iscsi/iscsi_target_tpg.c
+++ b/drivers/target/iscsi/iscsi_target_tpg.c
@@ -4,7 +4,7 @@
  *
  * (c) Copyright 2007-2013 Datera, Inc.
  *
- * Author: Nicholas A. Bellinger <nab@linux-iscsi.org>
+ * Author: Nicholas A. Bellinger <nab@kernel.org>
  *
  ******************************************************************************/
 
diff --git a/drivers/target/iscsi/iscsi_target_util.c b/drivers/target/iscsi/iscsi_target_util.c
index 91a75a4a7cc1..81f5f898dde3 100644
--- a/drivers/target/iscsi/iscsi_target_util.c
+++ b/drivers/target/iscsi/iscsi_target_util.c
@@ -4,7 +4,7 @@
  *
  * (c) Copyright 2007-2013 Datera, Inc.
  *
- * Author: Nicholas A. Bellinger <nab@linux-iscsi.org>
+ * Author: Nicholas A. Bellinger <nab@kernel.org>
  *
  ******************************************************************************/
 
diff --git a/drivers/target/target_core_configfs.c b/drivers/target/target_core_configfs.c
index 936e5ff1b209..bcbf2573d203 100644
--- a/drivers/target/target_core_configfs.c
+++ b/drivers/target/target_core_configfs.c
@@ -3752,7 +3752,7 @@ static void __exit target_core_exit_configfs(void)
 }
 
 MODULE_DESCRIPTION("Target_Core_Mod/ConfigFS");
-MODULE_AUTHOR("nab@Linux-iSCSI.org");
+MODULE_AUTHOR("nab@kernel.org");
 MODULE_LICENSE("GPL");
 
 module_init(target_core_init_configfs);
diff --git a/drivers/target/target_core_fabric_configfs.c b/drivers/target/target_core_fabric_configfs.c
index b7c637644cd4..8867f3d53665 100644
--- a/drivers/target/target_core_fabric_configfs.c
+++ b/drivers/target/target_core_fabric_configfs.c
@@ -7,7 +7,7 @@
  *
  * (c) Copyright 2010-2013 Datera, Inc.
  *
- * Nicholas A. Bellinger <nab@linux-iscsi.org>
+ * Nicholas A. Bellinger <nab@kernel.org>
 *
  ****************************************************************************/
 
diff --git a/drivers/target/target_core_fabric_lib.c b/drivers/target/target_core_fabric_lib.c
index 6600ae44f29d..b33e7412c4b6 100644
--- a/drivers/target/target_core_fabric_lib.c
+++ b/drivers/target/target_core_fabric_lib.c
@@ -7,7 +7,7 @@
  *
  * (c) Copyright 2010-2013 Datera, Inc.
  *
- * Nicholas A. Bellinger <nab@linux-iscsi.org>
+ * Nicholas A. Bellinger <nab@kernel.org>
  *
  ******************************************************************************/
 
diff --git a/drivers/target/target_core_file.c b/drivers/target/target_core_file.c
index 4d447520bab8..c95962e0feac 100644
--- a/drivers/target/target_core_file.c
+++ b/drivers/target/target_core_file.c
@@ -943,7 +943,7 @@ static void __exit fileio_module_exit(void)
 }
 
 MODULE_DESCRIPTION("TCM FILEIO subsystem plugin");
-MODULE_AUTHOR("nab@Linux-iSCSI.org");
+MODULE_AUTHOR("nab@kernel.org");
 MODULE_LICENSE("GPL");
 
 module_init(fileio_module_init);
diff --git a/drivers/target/target_core_iblock.c b/drivers/target/target_core_iblock.c
index a6a06a5f7483..08cac93640ce 100644
--- a/drivers/target/target_core_iblock.c
+++ b/drivers/target/target_core_iblock.c
@@ -1189,7 +1189,7 @@ static void __exit iblock_module_exit(void)
 }
 
 MODULE_DESCRIPTION("TCM IBLOCK subsystem plugin");
-MODULE_AUTHOR("nab@Linux-iSCSI.org");
+MODULE_AUTHOR("nab@kernel.org");
 MODULE_LICENSE("GPL");
 
 module_init(iblock_module_init);
diff --git a/drivers/target/target_core_pscsi.c b/drivers/target/target_core_pscsi.c
index 0d4f09693ef4..fe9a4253c5b9 100644
--- a/drivers/target/target_core_pscsi.c
+++ b/drivers/target/target_core_pscsi.c
@@ -1062,7 +1062,7 @@ static void __exit pscsi_module_exit(void)
 }
 
 MODULE_DESCRIPTION("TCM PSCSI subsystem plugin");
-MODULE_AUTHOR("nab@Linux-iSCSI.org");
+MODULE_AUTHOR("nab@kernel.org");
 MODULE_LICENSE("GPL");
 
 module_init(pscsi_module_init);
diff --git a/drivers/target/target_core_stat.c b/drivers/target/target_core_stat.c
index c42cbde8a31b..60e485753d29 100644
--- a/drivers/target/target_core_stat.c
+++ b/drivers/target/target_core_stat.c
@@ -7,7 +7,7 @@
  *
  * (c) Copyright 2006-2013 Datera, Inc.
  *
- * Nicholas A. Bellinger <nab@linux-iscsi.org>
+ * Nicholas A. Bellinger <nab@kernel.org>
  *
  ******************************************************************************/
 
